highlighter: "rouge"
# - markdown: "kramdown"

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post

plugins:
  - jekyll-sitemap

title: "Manton Reece"
tagline: ""
description: "Follow <a href=\"https://micro.blog/manton\">@manton on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/manton\">@manton on Micro.blog</a>."
baseurl: ""
url: "https://manton.micro.blog"
markdown: "kramdown"
username: "manton"
microblog_user: "manton"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Manton Reece"
name: "Manton Reece"
gravatar_hash: "d848ac9a3c64d1b73563895892cb2819"
avatar: "https://micro.blog/manton/avatar.jpg"
full_name: "Manton Reece"
bio: ""
twitter_username: ""
github_username: "manton"
instagram_username: "mantontest"
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Indiana-Starke"
site_id: "10"
gems: ["jekyll-paginate"]
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"
itunes_author: "Manton Reece"