# Dependencies
# - markdown:         redcarpet
highlighter:      pygments

# Permalinks
# - permalink:        pretty
# - relative_permalinks: true

# Setup
# - title:            '[TITLE]'
# - tagline:          'A Jekyll theme'
# - description:      "Powered by <a href=\"http://micro.blog/\">Micro.blog</a>."
# - url:              "http://[HOSTNAME]"
# - base# - url:          "[PATH]"
# - user# - name: "[USERNAME]"

# - author:
  # - name:           'Mark Otto'
  # - url:            https://twitter.com/mdo

# - paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

title: "Manton Reece"
tagline: ""
description: "Powered by <a href=\"http://micro.blog/\">Micro.blog</a>."
credits: "Powered by <a href=\"http://micro.blog/\">Micro.blog</a>."
baseurl: ""
url: "http://micro.manton.org"
markdown: "kramdown"
username: "manton"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Manton Reece"
name: "Manton Reece"
gravatar_hash: "d848ac9a3c64d1b73563895892cb2819"
avatar: "http://www.gravatar.com/avatar/d848ac9a3c64d1b73563895892cb2819?s=160"
full_name: "Manton Reece"
bio: ""
twitter_username: ""
github_username: "manton"
instagram_username: "mantontest"
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Indiana-Starke"